### ISSUE TITLE
epg failes to update on clients

### ISSUE THREAD

**Issue by vortex91** [cabernetwork/provider_epg_tvguide#2]
Based on testing i have done it would seem taht its not the size or lenght but probably invaalid charachters picked up.  As example if epg data for 2/12/2024 is used then it fails.

**Comment by rocky4546** [comment]
The url has changed.  pushing out a version update 0.1.13 today.

**Comment by vortex91** [comment]
I am not sure if thats the only reason.  Epg seems to still udpate.  What im stating is from time to time it stops and size of epg is not related to when it stops.  For example on 2/12/24 update failed for 16:00 data (pacific time) and after that it worked.  My best guess is that program data might have some invalid charachters in description such as < > ' " & and  maybe others which im not aware of?

**Comment by rocky4546** [comment]
ElementTree auto encodes the strings, so no issues with special characters.

**Comment by vortex91** [comment]
Well what i am certain of is that the size of xml does not matter and that its a preticular item within which causes issue.  I can provide ither cabernet logs or client log if you like.  test i have done so far
1. epg of xumo/pluto/daddy all in 1 request: works fine sometimes fails. when 
a. split epg into 3 request 1 per plugin.  xumo/pluto work daddy fails.
b. when daddy fails look at client side last time of epg data and try to update 1 hour after last time epg data made to client.  this works.  this tells me that in the timeframe in question something is causing epg update to fail on daddy/tvguide side.  
2. when epg for daddy works again on 2 days increase time frame to 5 days. (works)
a. when 5day epg for daddy fials to update to client reduce to 2 days and cleare data on server
b. 2 days works untill 3 days later when 5 days of data is reached at which point it fails.

Let me know if you want logs from client or server

**Comment by vortex91** [comment]
updated to latest and still same issue.  As of now 2/18/2024 4:00pm pacific time is last epg data which will update.

**Comment by vortex91** [comment]
so after 4:00 pm pacific time i was able to update epg without any issues.  im guessing that its specific guide data causing the issue and once that time period is gone then it works.

**Comment by rocky4546** [comment]
log shows no issues

**Comment by vortex91** [comment]
2024-02-18 23:28:34,233-INFO:epg2xml Connection dropped by client [Errno 32] Broken pipe

this is due to somethign in body of xml which causes issue.  WHen this happens i have deleted entire data folder and re-updated entire db but its fails again on same time.  I have also tried with 3 different clients.

**Comment by vortex91** [comment]
K it seems like client is timeing out from looking at client logs.  How can i edit either gui or options or code directly to remove EPG data of channels which do not have epg data.  Currently they are filling up the XML with channel name.  I want it to be blank in XML.

**Comment by rocky4546** [comment]
Use the channel editor to disable channels.

**Comment by vortex91** [comment]
I do not want to disable.  I want to be able to watch the channel.  I just dont want that channel to have epg info in XML since its just repeating its name over and over.
