### ISSUE TITLE
EGP Plugin JSON Decorator Error

### ISSUE THREAD

**Issue by bobbyllama** [cabernetwork/provider_epg_tvguide#4]
For the last day or two, the EGP plugin has been unable to pull data for DL from the TVG plugin. Updated to most current release. Channels still play, but every attempt to refresh EGP data results in the following console error for every channel:

2024-11-09 10:36:19,464-ERROR:decorators JSONError in function PluginEPG.get_uri_data(): Expecting value: line 1 column 1 (char 0)

**Comment by rocky4546** [comment]
Resolved in 0.1.14 EPG Plugin.

**Comment by bobbyllama** [comment]
thanks for such a quick reply. updated and the error is resolved. appreciate you!
