### ISSUE TITLE
Continuous error during EPG update.

### ISSUE THREAD

**Issue by ls-milkyway** [cabernetwork/provider_epg_tvguide#7]
Getting errors on all channels during epg refresh?

`ERROR:decorators JSONError in function PluginEPG.get_uri_data(): Expecting value: line 1 column 1 (char 0)`

**Comment by rocky4546** [comment]
provider url changed, updated 1.16 with new urls.

**Comment by NYZack** [comment]
I updated to 1.16 and am still getting the same error.

**Comment by subby2006** [comment]
tvguide may be blocking your ip. i'm getting a 403 when trying to access the website

**Comment by rocky4546** [comment]
If you are having a 403 error (DDoS attack), try the following.  Disable EPG in DL so Cabernet does not try to connect to TVG.  Let this sit for over 24 hours, then try to hit the web site.  Keep EPG down until TVG website works again, then re-enable EPG.  Make sure to have the latest version of the TVG plugin.
